const QUOTES = [
  { text: 'El dolor que sentís hoy es la fuerza que vas a sentir mañana.', author: null },
  { text: 'No contés los días. Hacé que los días cuenten.', author: 'Muhammad Ali' },
  { text: 'El único mal entrenamiento es el que no hiciste.', author: null },
  { text: 'Tu cuerpo puede soportar casi cualquier cosa. Es tu mente a la que tenés que convencer.', author: null },
  { text: 'El éxito no se regala. Se suda.', author: null },
  { text: 'Cada rep te acerca a quien querés ser.', author: null },
  { text: 'No hay atajos para ningún lugar que valga la pena ir.', author: null },
  { text: 'La disciplina es hacer lo que tenés que hacer, aunque no tengas ganas.', author: null },
  { text: 'No te compares con otros. Competí con quien eras ayer.', author: null },
  { text: 'Los grandes resultados requieren grandes ambiciones.', author: 'Heráclito' },
  { text: 'El cuerpo logra lo que la mente cree.', author: null },
  { text: 'Empezá donde estás. Usá lo que tenés. Hacé lo que podés.', author: 'Arthur Ashe' },
  { text: 'La constancia hace al campeón.', author: null },
  { text: 'No pares cuando estés cansado. Pará cuando termines.', author: null },
  { text: 'Cada día es una nueva oportunidad de mejorar.', author: null },
  { text: 'El límite solo existe en la mente.', author: null },
  { text: 'Sé más fuerte que tu excusa más fuerte.', author: null },
  { text: 'El progreso, no la perfección, es la meta.', author: null },
  { text: 'Un año de consistencia supera a un mes de intensidad.', author: null },
  { text: 'La motivación te arranca. El hábito te sostiene.', author: null },
  { text: 'Hacé hoy lo que otros no harán para tener mañana lo que otros no tendrán.', author: null },
  { text: 'La fuerza no viene de la capacidad física. Viene de una voluntad indomable.', author: 'Gandhi' },
  { text: 'No es la montaña que conquistamos, sino a nosotros mismos.', author: 'Edmund Hillary' },
  { text: 'Cuida tu cuerpo. Es el único lugar que tenés para vivir.', author: 'Jim Rohn' },
  { text: 'La única manera de hacer un gran trabajo es amar lo que hacés.', author: 'Steve Jobs' },
  { text: 'Cada entrenamiento es un depósito en el banco de tu salud.', author: null },
  { text: 'No existe el imposible para quién actúa.', author: 'Alejandro Magno' },
  { text: 'Transformá el sudor de hoy en el éxito de mañana.', author: null },
  { text: 'Rendirse siempre es la opción más fácil, pero nunca la mejor.', author: null },
  { text: 'El secreto del éxito es la consistencia de propósito.', author: 'Benjamin Disraeli' },
  { text: 'Los campeones entrenan, los perdedores se quejan.', author: null },
  { text: 'Vos sos más fuerte de lo que creés.', author: null },
  { text: 'Un cuerpo en movimiento tiende a seguir moviéndose.', author: null },
  { text: 'La dedicación de hoy construye el cuerpo de mañana.', author: null },
  { text: 'Tomate un momento. Después volvé y aplastá ese entrenamiento.', author: null },
  { text: 'El atletismo no es un deporte, es un estilo de vida.', author: null },
  { text: 'Hacé que tu yo del futuro te lo agradezca.', author: null },
  { text: 'No importa qué tan lento vayas, siempre y cuando no pares.', author: 'Confucio' },
  { text: 'La voluntad de ganar no es nada sin la voluntad de prepararse.', author: 'Vince Lombardi' },
  { text: 'Cada serie que hacés te hace más fuerte. Cada serie que saltás no.', author: null },
  { text: 'El éxito es la suma de pequeños esfuerzos repetidos día a día.', author: 'Robert Collier' },
  { text: 'Entrená duro o volvé a casa.', author: null },
  { text: 'Lo que no te mata te hace más fuerte.', author: 'Nietzsche' },
  { text: 'El cansancio es temporal. El orgullo es para siempre.', author: null },
  { text: 'Convertite en el tipo de persona que no necesita motivación.', author: null },
  { text: 'Los músculos se construyen fuera del gym, durante el descanso. Pero primero hay que ganárselos.', author: null },
  { text: 'Un entrenamiento al día mantiene las excusas alejadas.', author: null },
  { text: 'No hay ascensor hacia el éxito. Hay que tomar las escaleras.', author: null },
  { text: 'El único fracaso es no intentarlo.', author: null },
  { text: 'Superá tus límites de ayer con el trabajo de hoy.', author: null },
  { text: 'La consistencia es lo que transforma el promedio en excelencia.', author: null },
  { text: 'Hacé lo difícil ahora para que lo imposible sea posible después.', author: null },
  { text: 'Tu única competencia sos vos mismo.', author: null },
  { text: 'Un cuerpo fuerte es el primer paso hacia una mente fuerte.', author: null },
  { text: 'Nunca te arrepentís de un entrenamiento que hiciste.', author: null },
  { text: 'La excelencia es un hábito, no un acto.', author: 'Aristóteles' },
  { text: 'Entrenar no es un castigo. Es un privilegio.', author: null },
  { text: 'Hoy puede doler. Mañana se festeja.', author: null },
  { text: 'Ponete los auriculares y destrozá ese entrenamiento.', author: null },
  { text: 'El mejor proyecto en el que podés trabajar sos vos.', author: null },
]

export function useDailyMotivation() {
  const dayOfYear = Math.floor(
    (Date.now() - new Date(new Date().getFullYear(), 0, 0).getTime()) / 86400000
  )
  const quote = QUOTES[dayOfYear % QUOTES.length]!
  return quote
}
